### ISSUE TITLE
Thank you for snippet

### ISSUE THREAD

**Issue by wpfdev** [Calabonga/Calabonga.Catalog#1]
Hi Sergey, you have done a good project, it looks very similar to my boilerplate for asp.net projects. But I haven't found in this project any examples/implementations the standalone service for scheduling jobs or tasks. Have you ever implemented a scheduling task service?
Thank you so much for a snippet for scaffolding all classes!

**Comment by Calabonga** [comment]
Hi wpfdev, thank you for your attention to my solution. Of course, I have an implementation of this kind of service. Especially for you I create a post in my [blog](https://www.calabonga.net/blog/post/asp-net-core-2-2-the-standalone-service-for-scheduling-jobs) where I provide three base classes and two examples of using. Feel free to write comments for this post.

Video on [Youtube](https://www.youtube.com/playlist?list=PLIB8be7sunXOiIeeUa6yItyHpLtKG9gqQ)
